### ISSUE TITLE
send* RPCs in the wallet should return the "fee reason"

### ISSUE THREAD

**Issue by MarcoFalke** [MarcoFalke/bitcoin-core#22]
When the wallet funds a transaction, it needs to add inputs until all output amounts as well as the fee are satisfied. The feerate is either set explicitly by the user or estimated.

To aid debugging, the fee reason should be reported to the user. For most wallet RPCs this is a breaking API change, so I suggest to make it an option like `verbose=1 (default=0)`.

#### Useful skills:

Bitcoin Core wallet, RPC interface, functional tests.

#### Want to work on this issue?

The purpose of the `good first issue` label is to highlight which issues are suitable for a new contributor without a deep understanding of the codebase.

You do not need to request permission to start working on this. You are encouraged to comment on the issue if you are planning to work on it. This will help other contributors monitor which issues are actively being addressed and is also an effective way to request assistance if and when you need it.

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by MarcoFalke** [comment]
Please leave a comment if you intend to work on this or let me know if you have any questions.

**Comment by stackman27** [comment]
Hey MarcoFalke, I am very interested in working on this issue

**Comment by MarcoFalke** [comment]
Great! I suggest you familiarize yourself with the RPC interface and how to compile Bitcoin Core and run the tests.

Let me know if you have any questions.

**Comment by stackman27** [comment]
Okay Thank you!

**Comment by stackman27** [comment]
Hey Marco, I just had few questions regarding adding fee reason. In rpcwallet.cpp i have found that fundrawtransaction let us input a manual feerate and settxfee <n> calculates automatic fee rate if n = 0. So, I am trying to display the fee reason output in gettransaction, but i just can't seem to connect the gettransaction and fundrawtransaction. Do you have any suggestions? Thankyou

**Comment by MarcoFalke** [comment]
There is a function called `CreateTransaction`. In the last line it logs the fee reason.

```cpp
    WalletLogPrintf("Fee Calculation: Fee:%d Bytes:%u Needed:%d Tgt:%d (requested %d) Reason:\"%s\" Decay %.5f: Estimation: (%g - %g) %.2f%% %.1f/(%.1f %d mem %.1f out) Fail: (%g - %g) %.2f%% %.1f/(%.1f %d mem %.1f out)\n",
              nFeeRet, nBytes, nFeeNeeded, feeCalc.returnedTarget, feeCalc.desiredTarget, StringForFeeReason(feeCalc.reason), feeCalc.est.decay,
              feeCalc.est.pass.start, feeCalc.est.pass.end,
              100 * feeCalc.est.pass.withinTarget / (feeCalc.est.pass.totalConfirmed + feeCalc.est.pass.inMempool + feeCalc.est.pass.leftMempool),
              feeCalc.est.pass.withinTarget, feeCalc.est.pass.totalConfirmed, feeCalc.est.pass.inMempool, feeCalc.est.pass.leftMempool,
              feeCalc.est.fail.start, feeCalc.est.fail.end,
              100 * feeCalc.est.fail.withinTarget / (feeCalc.est.fail.totalConfirmed + feeCalc.est.fail.inMempool + feeCalc.est.fail.leftMempool),
              feeCalc.est.fail.withinTarget, feeCalc.est.fail.totalConfirmed, feeCalc.est.fail.inMempool, feeCalc.est.fail.leftMempool);
    return true;
```

I think all you need to do is return the `feeCalc.reason` from this function.

**Comment by stackman27** [comment]
Okay i will look into it. Thank you very much!

**Comment by stackman27** [comment]
Hey Marco, while returning '''feeCalc.reason''' in send* RPC functions, i would have to modify their current return type and i don't think that would be an efficient option considering all the functional tests. Is there anything i am missing or is there any other viable options? Thank you

**Comment by MarcoFalke** [comment]
For most wallet RPCs this is a breaking API change, so I suggest to make it an option like verbose=1 (default=0).

**Comment by amitiuttarwar** [comment]
@MarcoFalke are you recommending adding a field "verbose", then if that is set to true show the fee reason? or are you referring to verbose as an example of a field that has a default option?

**Comment by MarcoFalke** [comment]
> are you recommending adding a field "verbose", then if that is set to true show the fee reason?

Yes. Sorry if that was unclear.

**Comment by amitiuttarwar** [comment]
oh okay. @stackman27 caught your drift and is headed down that path, but I was surprised by the idea of verbose for one additional field, so thought I'd check.

carry on :)

**Comment by stackman27** [comment]
> There is a function called `CreateTransaction`. In the last line it logs the fee reason.
> 
> ```c++
>     WalletLogPrintf("Fee Calculation: Fee:%d Bytes:%u Needed:%d Tgt:%d (requested %d) Reason:\"%s\" Decay %.5f: Estimation: (%g - %g) %.2f%% %.1f/(%.1f %d mem %.1f out) Fail: (%g - %g) %.2f%% %.1f/(%.1f %d mem %.1f out)\n",
>               nFeeRet, nBytes, nFeeNeeded, feeCalc.returnedTarget, feeCalc.desiredTarget, StringForFeeReason(feeCalc.reason), feeCalc.est.decay,
>               feeCalc.est.pass.start, feeCalc.est.pass.end,
>               100 * feeCalc.est.pass.withinTarget / (feeCalc.est.pass.totalConfirmed + feeCalc.est.pass.inMempool + feeCalc.est.pass.leftMempool),
>               feeCalc.est.pass.withinTarget, feeCalc.est.pass.totalConfirmed, feeCalc.est.pass.inMempool, feeCalc.est.pass.leftMempool,
>               feeCalc.est.fail.start, feeCalc.est.fail.end,
>               100 * feeCalc.est.fail.withinTarget / (feeCalc.est.fail.totalConfirmed + feeCalc.est.fail.inMempool + feeCalc.est.fail.leftMempool),
>               feeCalc.est.fail.withinTarget, feeCalc.est.fail.totalConfirmed, feeCalc.est.fail.inMempool, feeCalc.est.fail.leftMempool);
>     return true;
> ```
> 
> I think all you need to do is return the `feeCalc.reason` from this function.

Hey Marco, so the function createTransaction returns a boolean value. So, how would i return a string feeCalc.reason from the function? Am i supposed to store the value somewhere else and retrieve it in sendrpc calls? I found CWalletTx class in wallet.h line(269) that could be useful. Do you have any other suggestion? Thank you

**Comment by MarcoFalke** [comment]
values can be returned in function parameters as well. For example,

```cpp
void sum(int a, int b, int& ret) {ret=a+b;}
```
is a function with void return type that returns the result as a parameter

**Comment by stackman27** [comment]
Hey Marco, I made all the changes and its been over 2 weeks and I still haven't gotten any response on my PR. Is there anything I'm doing wrong. Can you please verify what's happening? Thank you

**Comment by MarcoFalke** [comment]
Sorry I got side-tracked. I'll take a look soon.

**Comment by stackman27** [comment]
For sure! Thank you very much
