### ISSUE TITLE
test: Make scriptnum test a unit test

### ISSUE THREAD

**Issue by MarcoFalke** [MarcoFalke/bitcoin-core#24]
The scriptnum tests (https://github.com/bitcoin/bitcoin/pull/14816) is a roundtrip test of the test framwork. Thus, it would be better suited as a unit test. This is now possible with the introduction of the unit test module for the functional tests. See https://github.com/bitcoin/bitcoin/pull/18576

#### Useful skills:

Basics of the Bitcoin Core functional test framework.

#### Want to work on this issue?

The purpose of the `good first issue` label is to highlight which issues are suitable for a new contributor without a deep understanding of the codebase.

You do not need to request permission to start working on this. You are encouraged to comment on the issue if you are planning to work on it. This will help other contributors monitor which issues are actively being addressed and is also an effective way to request assistance if and when you need it.

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by gillichu** [comment]
Hi Marco! I'd like to work on this! :)

**Comment by MarcoFalke** [comment]
@gillichu Great! Before you start contributing, familiarize yourself with the Bitcoin Core build system and tests. Refer to the documentation in the repository on how to build Bitcoin Core and how to run the unit and functional tests. Once that is done, you are all set and can start working on this issue.

If you need more help getting started, please refer to the following resources:

* https://medium.com/@amitiu/onboarding-to-bitcoin-core-7c1a83b20365
* https://jonatack.github.io/articles/how-to-review-pull-requests-in-bitcoin-core

Let me know if you have any questions.
