### ISSUE TITLE
[WIP] Splitting up the GUI into another project

### ISSUE THREAD

**Issue by MarcoFalke** [MarcoFalke/bitcoin-core#26]
## Goals

Splitting up the GUI (and splitting out modules in general) has been brought up often in recent years. Now that the GUI is primarily connected through interfaces with a bitcoin node, it seems an appropriate time to revive this discussion.

Before looking for solutions, we should define a set of goals that we want to achieve. I will start with some ideas to get started and I hope that others will chime in to share and prioritize their goals.

### Separate issue and patch management

It is currently not possible to subscribe to only a subset of modules in Bitcoin Core, or exclude modules from issue and patch notifications. While it is possible to reactively mute conversations in the stream of all ongoing discussions, there is no way to proactively achieve this. Moreover, the list of open issues and pull request will always include GUI related ones by default. Only with [filters](https://github.com/bitcoin/bitcoin/pulls?q=is%3Aopen+is%3Apr+-label%3AGUI) it is possible to hide them.

### More focused review and interests

Long term goals of the GUI are partially unclear #17395 . Bitcoin Core developers are generally fluent on the command line. Thus, they might not be interested or motivated to review improvements to the GUI, which might not affect their workflow on the command line at all.  Splitting up the GUI will hopefully attract similar minded people to a project whose primary goal is to build and improve the GUI.

### Maintain high quality assurance

The quality of the GUI (and even more importantly Bitcoin Core in general) must not degrade. This means that code review itself is not negatively affected by splitting the GUI, but also the integration of the GUI into the rest of Bitcoin Core. One issue could arise when arbitrary version-combinations are allowed. We are struggling hard to test against all supported versions of Boost. Making the GUI version another dimension is going to make testing impossible.

### The GUI *is* Bitcoin Core

When a user downloads Bitcoin Core from our website (or another package manager) they expect the GUI to be included. This should not change (at least not as a result of splitting up the GUI into another project).

Similarly, when building Bitcoin Core, the gui should still be built when `--with-gui` is specified.

**Comment by MarcoFalke** [comment]
## Solution: monotree

###

TODO explain

### Illustration

For illustrative purposes I have split up the functional tests into a separate repo. A merge commit in bitcoin/bitcoin would look like commit c9c3e3e

**Comment by MarcoFalke** [comment]
### Illustration

For illustrative purposes I have split up the functional tests into a separate repo. A merge commit in bitcoin/bitcoin would look like commit c9c3e3e

**Comment by ryanofsky** [comment]
Seems fine to me to create bitcoin-core/gui fork of bitcoin if it helps manage issues and pull requests. It seems like an easy thing to experiment with and abandon it it doesn't help.

My impression is that it seems like kind of a workaround for github not providing a very good issue tracker or code review tool that lets you categorize and assign things to people.

**Comment by ryanofsky** [comment]
One question would be how exactly would you want to handle a pr like #18115 that changes gui and wallet code? Allow it? Reject it and require the submitter to submit multiple PRs as a workaround?

**Comment by troygiorshev** [comment]
An additional benefit to this change is the allowance for an increased amount of UI/UX discussion.  Such discussions can be fairly deep and non-technical, but are very important.  Right now they would clog the repo as they're conceptually "far" from the usual.  There has been some great talk along the lines of [this comment](https://github.com/bitcoin/bitcoin/issues/17395#issuecomment-55033998) (especially the last paragraph).  A separate repo would be a great way to let even more of that happen.

**Comment by troygiorshev** [comment]
One possible solution to overlapping PRs is the following: PRs that overlap should be done as a single PR in the main repo (and similarly for issues).  The correct description of the two repos (GUI and Main) would not be "GUI-related and non-GUI", but instead "GUI-only and main".  We would not, say, ban GUI discussion in the main repo.  This split wouldn't attempt to be a perfect partition, just that any overlap is clearly one-sided.

**Comment by MarcoFalke** [comment]
Thanks everyone for the input, I will open a pull in the main repo in a second.
