### ISSUE TITLE
upgradewallet rpc warnings and error

### ISSUE THREAD

**Issue by MarcoFalke** [MarcoFalke/bitcoin-core#28]

**Comment by nar77** [comment]
> 

Nar110

**Comment by stackman27** [comment]
Hi Marco, can you give me more details on this issue? Would love to work on more RPC wallet related stuff. Thank you

**Comment by MarcoFalke** [comment]
Sure. The problem is that `upgradewallet` does not return warnings, even if they occur in the RPC.

See https://github.com/bitcoin/bitcoin/blob/301959fa7482cf749504864789e6f9f4470b8bb6/src/wallet/rpcwallet.cpp#L4462

**Comment by stackman27** [comment]
Okay i'd love to work on this. Also just making sure the warning details is set in `UpgradeWallet` function in `wallet.cpp` right?

**Comment by stackman27** [comment]
Just to expand on that, do i specify when to give warnings or is that already set?

**Comment by MarcoFalke** [comment]
There are other RPCs that already return the warnings. You can just copy from them

**Comment by stackman27** [comment]
The warnings variable from `upgradewallet` in rpcwallet.cpp seems to be passed onto `UpgradeWallet` function in wallet.cpp, but it's not being used in any way whatsoever. Do you want me to brainstorm specific warnings and log them out or is there a list already in place?

**Comment by MarcoFalke** [comment]
Oh, good catch. No, you don't need to add warnings. I think removing the `warnings` symbols is fine because they are unused. Though, the RPC also needs its return result properly documented. E.g. the `error` is not unused, but returned.

**Comment by stackman27** [comment]
okay sounds good! I'll clean up the documentation and create a PR. And just making sure `error` is of type `string` right?

**Comment by MarcoFalke** [comment]
jup, thanks!

**Comment by stackman27** [comment]
https://github.com/bitcoin/bitcoin/pull/20139

**Comment by MarcoFalke** [comment]
Thanks
